package com.cuuw619.fuxapi;
import com.cuuw619.fuxapi.config.FuxSettingsRegistry;import net.minecraft.client.Minecraft;import net.minecraft.client.gui.GuiGraphics;import net.minecraft.client.gui.components.Button;import net.minecraft.client.gui.screens.Screen;import net.minecraft.network.chat.Component;
public final class FuxHudEditorScreen extends Screen{private final Screen parent;private String dragging;private float dragOffsetX,dragOffsetY;public FuxHudEditorScreen(Screen parent){super(Component.literal("Fux HUD Editor"));this.parent=parent;}
@Override protected void init(){addRenderableWidget(Button.builder(Component.literal("Reset layout"),b->FuxHudLayout.reset()).bounds(width/2-145,height-34,90,20).build());addRenderableWidget(Button.builder(Component.literal("Done"),b->onClose()).bounds(width/2+55,height-34,90,20).build());}
@Override public void render(GuiGraphics g,int mx,int my,float pt){g.fill(0,0,width,height,0xD9000000);int a=accent();g.drawCenteredString(font,Component.literal("FUX HUD EDITOR"),width/2,18,0xFFFFFFFF);g.drawCenteredString(font,Component.literal("Drag to move • mouse wheel to resize • changes save automatically"),width/2,34,0xFF777D88);drawGrid(g);drawCompass(g,a);drawInfo(g,a);drawTarget(g,a);super.render(g,mx,my,pt);}
private void drawGrid(GuiGraphics g){for(int x=0;x<width;x+=40)g.fill(x,0,x+1,height,0x182A2F38);for(int y=0;y<height;y+=40)g.fill(0,y,width,y+1,0x182A2F38);}
private void drawCompass(GuiGraphics g,int a){FuxHudLayout.Data d=FuxHudLayout.data();int cx=Math.round(d.compassX*width),cy=Math.round(d.compassY*height),w=Math.round(Math.min(720,width-80)*d.compassScale);g.fill(cx-w/2,cy,cx+w/2,cy+42,0x30101016);g.fill(cx-w/2,cy+41,cx+w/2,cy+43,a);g.drawCenteredString(font,Component.literal("COMPASS  ×"+String.format("%.2f",d.compassScale)),cx,cy+15,0xFFFFFFFF);label(g,"Compass",cx,cy-13,a);}
private void drawInfo(GuiGraphics g,int a){FuxHudLayout.Data d=FuxHudLayout.data();int x=Math.round(d.infoX*width),y=Math.round(d.infoY*height);g.pose().pushPose();g.pose().translate(x,y,0);g.pose().scale(d.infoScale,d.infoScale,1);g.drawString(font,"144 FPS",-65,0,0xFFFFFFFF,false);g.drawString(font,"12:34:56",-65,16,a,false);g.pose().popPose();label(g,"FPS / Clock ×"+String.format("%.2f",d.infoScale),x-32,y-13,a);}
private void drawTarget(GuiGraphics g,int a){FuxHudLayout.Data d=FuxHudLayout.data();int x=Math.round(d.targetEspX*width),y=Math.round(d.targetEspY*height),s=Math.round(54*d.targetEspScale);g.fill(x-s/2,y-s/2,x+s/2,y+s/2,0x24101016);g.fill(x-s/2,y-s/2,x-s/2+2,y+s/2,a);g.drawCenteredString(font,Component.literal("TARGET ESP ×"+String.format("%.2f",d.targetEspScale)),x,y-4,0xFFFFFFFF);label(g,"Target ESP",x,y-s/2-13,a);}
private void label(GuiGraphics g,String text,int x,int y,int a){int w=font.width(text)+10;g.fill(x-w/2,y-2,x+w/2,y+12,0xC0101218);g.drawCenteredString(font,Component.literal(text),x,y,a);}
@Override public boolean mouseClicked(double mx,double my,int button){if(button!=0)return super.mouseClicked(mx,my,button);if(hitCompass(mx,my)){begin("compass",mx,my);return true;}if(hitInfo(mx,my)){begin("info",mx,my);return true;}if(hitTarget(mx,my)){begin("targetEsp",mx,my);return true;}return super.mouseClicked(mx,my,button);}
private void begin(String id,double mx,double my){dragging=id;FuxHudLayout.Data d=FuxHudLayout.data();float x=switch(id){case "compass"->d.compassX;case "info"->d.infoX;default->d.targetEspX;}*width,y=switch(id){case "compass"->d.compassY;case "info"->d.infoY;default->d.targetEspY;}*height;dragOffsetX=(float)mx-x;dragOffsetY=(float)my-y;}
@Override public boolean mouseDragged(double mx,double my,int button,double dx,double dy){if(button!=0||dragging==null)return super.mouseDragged(mx,my,button,dx,dy);FuxHudLayout.Data d=FuxHudLayout.data();float nx=((float)mx-dragOffsetX)/Math.max(1,width),ny=((float)my-dragOffsetY)/Math.max(1,height);nx=Math.max(.02F,Math.min(.98F,nx));ny=Math.max(.03F,Math.min(.92F,ny));switch(dragging){case "compass"->{d.compassX=nx;d.compassY=ny;}case "info"->{d.infoX=nx;d.infoY=ny;}default->{d.targetEspX=nx;d.targetEspY=ny;}}FuxHudLayout.clamp();return true;}
@Override public boolean mouseScrolled(double mx,double my,double sx,double sy){FuxHudLayout.Data d=FuxHudLayout.data();if(hitCompass(mx,my))d.compassScale=clampScale(d.compassScale+(.05F*(float)sy));else if(hitInfo(mx,my))d.infoScale=clampScale(d.infoScale+(.05F*(float)sy));else if(hitTarget(mx,my))d.targetEspScale=clampScale(d.targetEspScale+(.05F*(float)sy));else return super.mouseScrolled(mx,my,sx,sy);FuxHudLayout.save();return true;}
private float clampScale(float v){return Math.max(.5F,Math.min(2F,v));}@Override public boolean mouseReleased(double mx,double my,int button){if(button==0&&dragging!=null){FuxHudLayout.save();dragging=null;return true;}return super.mouseReleased(mx,my,button);}@Override public void onClose(){FuxHudLayout.save();Minecraft.getInstance().setScreen(parent);}private boolean hitCompass(double mx,double my){FuxHudLayout.Data d=FuxHudLayout.data();int x=Math.round(d.compassX*width),y=Math.round(d.compassY*height),w=Math.round(Math.min(720,width-80)*d.compassScale);return mx>=x-w/2&&mx<=x+w/2&&my>=y-10&&my<=y+52;}private boolean hitInfo(double mx,double my){FuxHudLayout.Data d=FuxHudLayout.data();int x=Math.round(d.infoX*width),y=Math.round(d.infoY*height);return mx>=x-80*d.infoScale&&mx<=x+20*d.infoScale&&my>=y-10&&my<=y+42;}private boolean hitTarget(double mx,double my){FuxHudLayout.Data d=FuxHudLayout.data();int x=Math.round(d.targetEspX*width),y=Math.round(d.targetEspY*height),s=Math.round(40*d.targetEspScale);return mx>=x-s&&mx<=x+s&&my>=y-s&&my<=y+s;}private int accent(){return switch(FuxSettingsRegistry.ACCENT.get()){case "BLUE"->0xFF4F8CFF;case "GREEN"->0xFF45C98A;default->0xFF8B5CF6;};}}
